name: Deploy to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Download and Setup typst-ts-cli
        run: |
          curl -s -L https://github.com/Myriad-Dreamin/typst.ts/releases/download/v0.5.4/typst-ts-x86_64-unknown-linux-gnu.tar.gz -o typst-ts.tar.gz
          mkdir typst-ts
          tar -xzf typst-ts.tar.gz -C typst-ts
          echo "$(pwd)/typst-ts/typst-ts-x86_64-unknown-linux-gnu/bin" >> $GITHUB_PATH

      - name: Download and Setup Zola
        run: |
          curl -s -L https://github.com/getzola/zola/releases/download/v0.20.0/zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
          mkdir zola
          tar -xzf zola.tar.gz -C zola
          echo "$(pwd)/zola" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:all

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy ./public --project-name=my-blog
